### ISSUE TITLE
token invalid

### ISSUE THREAD

**Issue by BitCheats** [KMKINGMAN/Application-Bot#2]
its saying my token is invalid?

**Comment by mkurkar** [comment]
Create a filename .evn and put this info

ME_TOKEN = Bot Token 
ME_MONGO = MongoDB Url
- [x] Thx

**Comment by BitCheats** [comment]
I’ve already done that, am I not supposed to replace the “Bot Token” and “MongoDB url” with my bot token and mongo url?
